### PR TITLE
Add DPP to partitions restore list (for DPP-patched Lumia 525 devices).

### PR DESCRIPTION
**Pull request by dung11112003**

### CODE REVIEW

**Comment by TBM13** [comment]
Step 2) and 4) are missing.
anotacion 2018-12-17 193103

**Comment by dung11112003** [comment]
I deleted it (4 some reasons)

**Comment by sjrmac** [comment]
Has this been finalized?

**Comment by dung11112003** [comment]
Yeah

**Comment by feherneoh** [comment]
You are NOT supposed to restore the original DPP once patched
That DPP bug breaks thor2's detection too when the phone is first connected in flashmode, not normal mode, and the fix shouldn't affect anything but flashmode

**Pull request closed without merging**
